[versions]
ktor = "3.2.1"
logback = "1.5.18"

[libraries]
logback = { group = "ch.qos.logback", name = "logback-classic", version.ref = "logback" }

[plugins]
ktor = { id = "io.ktor.plugin", version.ref = "ktor" }
