ktor:
  deployment:
    port: 8080
    rootPath: /docuiqk
  application:
    modules:
      - com.example.ApplicationKt.main
database:
  url: jdbc:postgresql://localhost:5434/docuiqk
  user: docuiqk_user
  password: password123
logging:
  jooq:
    enabled: true