name: docuiqk

services:
  docuiqk_adminer:
    image: adminer:5.3.0
    restart: unless-stopped
    ports:
      - 8090:8080
    environment:
      - ADMINER_DESIGN=nette
    networks:
      - docuiqk-db-network
  docuiqk_db:
    image: postgres:17.4-alpine3.21
    restart: on-failure
    shm_size: 128mb
    environment:
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
      - DB_NAME=${DB_NAME}
      - DB_USER_NAME=${DB_USER_NAME}
      - DB_USER_PASSWORD=${DB_USER_PASSWORD}
      - TZ=UTC
    volumes:
      - docuiqk_db_data:/var/lib/postgresql/data
      - ./init-user-db.sh:/docker-entrypoint-initdb.d/init-user-db.sh
    ports:
      - '5434:5432'
    networks:
      - docuiqk-db-network
  docuiqk_minio:
    image: 'minio/minio:RELEASE.2025-07-23T15-54-02Z-cpuv1'
    environment:
      - MINIO_ROOT_USER=${MINIO_ROOT_USER}
      - MINIO_ROOT_PASSWORD=${MINIO_ROOT_PASSWORD}
    ports:
      - "9900:9000"
      - "9901:9001"
    command: ["server", "--console-address", ":9001", "/data"]
volumes:
  docuiqk_db_data:

networks:
  docuiqk-db-network:
    name: docuiqk-db-network
    driver: bridge